# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba7d0a8231469086b3746b96c55c3fd04940342dbc91d592e25a39dcda44d28109904121421cbf713298ac88aa5b90e287a42932bc121c11c48e28fde65a6ea8

test:
  secret_key_base: 8336e94c627d3714cc84e9d81818b497e950b1998505fce32b28b1c8c625a4ddedde5dec3818265cd19f0d9d71cbb0cb3f4bda8ffeb3057caab9ab03d9d597c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
